### ISSUE TITLE
Making faster Playlist class methods 

### ISSUE THREAD

**Issue by Mateus-Mannes** [Mateus-Mannes/musicanalysis#3]
I've commited the changes in the "pegar_generos" function that we've made Sunday (in the lookup branch). That made our "lookup for users" feature 60% faster, but It is still slow. I belive there many other things we can do to make the code faster. For example: 

--- AVOIDING USING API FUNCTIONS
*** In the init function we use "user_playlists(user, limit=5)" to get the playlists of the shearched user, and for the current user we use "me()" to get the current user id and then pass it through "user_playlists()". Doing that we are calling the Web Api two times to get the current user playlists, and we could use It just one time by opting for the "current_user_playlists(limit=50, offset=0)" function.

--- REFACTORING
***We are repeating ourselves in the code. For example, we are getting the artists of the playlists musics in "pegar_generos" and "pegar_artistas", moreover, we are repeating the "moda" calculation in those methods. I think we should refactor all methods in small functions, and use better names for variables, functions, etc .... (all in English).

What do you think ? I really belive that refactoring the code like I said is the most important thing to make it faster.

ps: I've made this repostorio public.

**Comment by marianamannes** [comment]
ok
