### ISSUE TITLE
User checker not working

### ISSUE THREAD

**Issue by Mateus-Mannes** [Mateus-Mannes/musicanalysis#5]
Hi @marianamannes , I have added the template in #2. But the function that you've made for check if the user name inputed exists didn't work for me. it just returns an HTTP error and pass through the try/except block:
`HTTP Error for GET to https://api.spotify.com/v1/users/mariana Mannes returned 400 due to Invalid username
127.0.0.1 - - [30/Aug/2020 13:54:14] "POST /look%20users HTTP/1.1" 200 -`
I maybe i've caused this, because I remember using it and it was working. Can you test it ?

**Comment by marianamannes** [comment]
Okay! It was just a typo. It works fine now.
